#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString* const PiPiOCEditPdfUnknownExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCOperatePdfUnknownExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCMultiOperatePdfUnknownExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCPagePdfUnknownExceptionName;

FOUNDATION_EXPORT NSString* const PiPiOCAppearanceExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCEditFieldExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCExtractExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCFieldCompatibilityExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCFillFieldExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCManageFieldExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCPageExceptionName;
FOUNDATION_EXPORT NSString* const PiPiOCMultiOperateExceptionName;
